### ISSUE TITLE
期望添加服务端渲支持

### ISSUE THREAD

**Issue by panghongye** [StructureBuilder/react-keep-alive#22]
我在next.js 上使用报错 document is not defined 

ReferenceError: document is not defined
    at Object.createStoreElement [as default] (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-keep-alive@2.1.0@react-keep-alive/cjs/utils/createStoreElement.js:5:24)
    at new KeepAliveProvider (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-keep-alive@2.1.0@react-keep-alive/cjs/components/Provider.js:49:58)
    at processChild (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-dom@16.8.6@react-dom/cjs/react-dom-server.node.development.js:2846:14)
    at resolve (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-dom@16.8.6@react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-dom@16.8.6@react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-dom@16.8.6@react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_react-dom@16.8.6@react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_next-server@8.1.0@next-server/dist/server/render.js:86:16)
    at renderPage (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_next-server@8.1.0@next-server/dist/server/render.js:211:20)
    at Function.value (/Users/panghongye/Desktop/Project/bemular-saas-website/.next/server/static/development/pages/_document.js:555:41)
    at Object.loadGetInitialProps (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_next-server@8.1.0@next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/panghongye/Desktop/Project/bemular-saas-website/node_modules/_next-server@8.1.0@next-server/dist/server/render.js:218:36)

**Comment by Sam618** [comment]
@panghongye 我要研究下哈

**Comment by Sam618** [comment]
@panghongye 发布了新版本，修正了这个问题，新版本（`react-keep-alive@2.4.0`）
